apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  storageClassName: postgres
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/postgres"