apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: config-backend
    envs:
      - ../backend/.env.$CI_ENVIRONMENT_TIER
resources:
  - backend.yaml
  - backend-hpa.yaml
